name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print secret unmasked
        run: |
          echo "::remove-matcher owner=secret::"
          echo "FLAG: $API_SECRET"
        env:
          API_SECRET: ${{ secrets.FLAG_SECRET }}
